CREATE TABLE IF NOT EXISTS `lending_records` (
    `id` CHAR(36) NOT NULL PRIMARY KEY,
    `user_id` CHAR(36) NOT NULL,
    `book_id` CHAR(36) NOT NULL,
    `borrow_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `return_date` TIMESTAMP NULL,
    `status` ENUM('borrowed', 'returned') NOT NULL DEFAULT 'borrowed',

    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`book_id`) REFERENCES `books`(`id`) ON DELETE RESTRICT
);