CREATE TABLE IF NOT EXISTS books (
    id CHAR(36) NOT NULL PRIMARY KEY,
    title VARCHAR(250) NOT NULL,
    author VARCHAR(100) NOT NULL,
    isbn VARCHAR(100) NOT NULL UNIQUE,
    category VARCHAR(100) NOT NULL,
    quantity INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100) NOT NULL,
    updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NULL DEFAULT NULL,
    deleted_at DATETIME NULL DEFAULT NULL,
    deleted_by VARCHAR(100) NULL DEFAULT NULL
);
